### ISSUE TITLE
Disable Page and Timing tracking for specific controllers

### ISSUE THREAD

**Issue by code-constructor** [tpitale/staccato-rails#15]
Hey Guys,

at first, thanks a lot for this awesome gem and the sub gem staccato!

I'm looking for a way to disable the automatic tracking for some controllers. In my use case, i have a controller namespace which is used for the delivery of the website and some namespaces for api stuff. So i need a way to disable the tracking for the api controllers.

AFAICS there is no switch in the code to turn on/off the tracking in the context of a specific controller. Or did i miss something?

It would be possible that i do the code implementation if you can give me a short overview how you would like to see the implementation in your code.

Thanks a lot and regards
Alex

**Comment by tpitale** [comment]
Because of the use of active support notifications, there’s not a controller-specific way to do this, currently.

We could go one of two ways. Make it so that a controller has to opt-in to tracking, or a config option that filters a set of controllers out. I’m not sure which will work or which I prefer. I’ll have to revisit what AS::Notifications provides.

**Comment by tpitale** [comment]
@code-constructor Please review the PR.
